DEFINT A-Z
'$DYNAMIC

DECLARE SUB AncientAI (e)
DECLARE SUB AncientFrames (e)
DECLARE SUB CloudAI (e)
DECLARE SUB CloudFrames (e)
DECLARE SUB MimrockAI (e)
DECLARE SUB MimrockFrames (e)
DECLARE SUB ShooterAI (e)
DECLARE SUB ShooterFrames (e)
DECLARE SUB SnakeAI (e)
DECLARE SUB SnakeFrames (e)
DECLARE SUB SpearAI (e)
DECLARE SUB SpearFrames (e)
DECLARE SUB WormAI (e)
DECLARE SUB WormFrames (e)

